service: interbank

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'logs:CreateLogGroup'
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource: '*'
  environment:
    NODE_ENV: ${opt:stage}
    SERVER_SECRET_KEY: ${self:custom.${opt:stage}.SERVER_SECRET_KEY}

functions:
  api:
    handler: dist/infra/server/lambda/ExpressLambda.handlerExpressLambda
    description: 'Interbank api'
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    timeout: 20

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4200
  dev:
    SERVER_SECRET_KEY: ${env:SERVER_SECRET_KEY,"-"}

package:
  individually: true
  include:
    - config
  exclude:
    - src/**
    - .editorconfig
    - .eslint*
    - .rc*
    - tsconfig.json
    - tsconfig.build.json
    - .nvmrc
    - .env
    - .env.example